### PR TITLE
Support for Swift6 and async/await

### PR DESCRIPTION
**Pull request by gennaro-safehill**

### CODE REVIEW

**Comment by MihaelIsaev** [comment]
Hey @gennaro-safehill, thanks for the great pull request! It looks good. Is it ready to be merged?

**Comment by gennaro-safehill** [comment]
> Hey @gennaro-safehill, thanks for the great pull request! It looks good. Is it ready to be merged?

You're welcome! I'm an open-sourcer and it's all about helping the community!
I'm testing the code out right now, I'll let you know

**Comment by MihaelIsaev** [comment]
Thank you @gennaro-safehill, once you confirm it works well I'm ready to merge and tag it as `v3.0.0`

**Comment by gennaro-safehill** [comment]
I run into some problems deploying this code to Heroku using Swift 6.
There are some problems with the buildpack.

Using Swift 5.10 works. There are no code changes, it's only about the `swift-tools-version` in `Package.swift`.
Testing the changes right now in staging.

**Comment by gennaro-safehill** [comment]
Hi folks. Just wanted to let you know that I wasn't able to test these changes in my production environment with Swift 6 because we use Heroku and the buildpack for Swift 6 has some compat issues.

I did test them with 5.10, and they work great!
We have 2 options:
1. Merge this code as is
2. Merge the 5.10 version at https://github.com/MihaelIsaev/FCM/pull/49 (there's only one line change on top of the changes proposed here setting the swift-tools-version to 5.10.0

Let me know what you prefer

**Comment by gennaro-safehill** [comment]
No blockers. See my message above

**Comment by MihaelIsaev** [comment]
@gennaro-safehill I think this will work great! I'm ready to merge and tag it as v3 once the README is updated. Could you please update the README as well?

**Comment by MihaelIsaev** [comment]
@gennaro-safehill Many thanks for your contribution! It is now available since `3.0.0-beta.1` tag.

**Pull request merged**
